server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: bcb-sms-service
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:${DB_PORT:5433}/bcb
    username: bcb
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  config:
    import:
    - optional:configserver:http://localhost:8888/
#  cloud:
#    config:
#      profile: default
  flyway:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:${DB_PORT:5433}/
    schemas: bcb
    user: bcb
    password: 123456