server:
  port: 8080
spring:
  application:
    name: bcb-client-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bcb
    username: bcb
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
    - optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: default
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
client-service:
  client: "client"
  default-value: "teste client"
