server:
  port: 8080
spring:
  application:
    name: bcb-client-service
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:${DB_PORT:5432}/bcb
    username: bcb
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  config:
    import:
    - optional:configserver:http://localhost:8888/
#  cloud:
#    config:
#      profile: default
  flyway:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:${DB_PORT:5432}/
    schemas: bcb
    user: bcb
    password: 123456
